<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="30732" started-at="2017-12-14T08:10:15Z" finished-at="2017-12-14T08:10:46Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="30732" started-at="2017-12-14T08:10:15Z" finished-at="2017-12-14T08:10:46Z">
      <class name="archivesManageModule.TestLogin2forpage4">
        <test-method status="PASS" signature="inialize()[pri:0, instance:archivesManageModule.TestLogin2forpage4@402f32ff]" name="inialize" is-config="true" duration-ms="9220" started-at="2017-12-14T16:10:15Z" finished-at="2017-12-14T16:10:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inialize -->
        <test-method status="FAIL" signature="login()[pri:0, instance:archivesManageModule.TestLogin2forpage4@402f32ff]" name="login" duration-ms="21492" started-at="2017-12-14T16:10:25Z" finished-at="2017-12-14T16:10:46Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at pages.LoginHomepage4.setMerchantId(LoginHomepage4.java:24)
	at archivesManageModule.TestLogin2forpage4.login(TestLogin2forpage4.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
      </class> <!-- archivesManageModule.TestLogin2forpage4 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
